#romeo-gpt/config.yml
cors:
  allowed_origins:
    - http://localhost:3000
    - https://romeogpt.com
    - https://romeo-gpt.vercel.app

models:
  embedding:
    model: text-embedding-ada-002
  completion:
    model: text-davinci-002
    max_tokens: 400


vector_settings:
  num_vectors: 4000
  prefix: "embedding"
  vector_dim: 1536
  distance_metric: "COSINE"


