#owl-vectores/docker-compose.yml
version: '3.9'
services:

  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - owl-vectores-db
    env_file:
      - .env
    volumes:
      - ./config.yml:/owl_vectores/config.yml
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=owl-vectores-db

  owl-vectores-db:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDISEARCH_ARGS=CONCURRENT_WRITE_MODE
    volumes:
      - owl-vectores-db:/var/lib/redis
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 2s
      timeout: 1m30s
      retries: 5
      start_period: 5s

volumes:
  owl-vectores-db:

