version: '3.8'
services:
  vector-db:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - vector-db:/data
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - vector-db
    environment:
      - REDIS_HOST=vector-db
      - REDIS_PORT=6379

volumes:
  vector-db:
